FROM docker.io/library/debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends fp-compiler fp-units-db fp-units-fcl libpq-dev libmariadb-dev-compat firebird-dev libsqlite3-dev ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /workspace
