program test_autoincrement;
{$mode ObjFPC}{$H+}
uses Classes, SysUtils, DeltaModel, DeltaModel.Fields, DeltaModel.ORM.Types,
  DeltaModel.ORM.DDL;
type
  TItem = class(TDeltaModel)
  private
    FId: TDFInt64Null;
    FCode: TDFIntNull;
  public
    procedure AfterConstruction; override;
  published
    property Id: TDFInt64Null read FId write FId;
    property Code: TDFIntNull read FCode write FCode;
  end;
procedure TItem.AfterConstruction;
begin
  inherited;
  TableName := 'dm_auto';
  Id.FieldName := 'id';
  Id.DBOptions := [dboPrimaryKey, dboAutoInc];
  Code.FieldName := 'code';
end;
var Checks: Integer;
procedure Check(Value: Boolean; const Msg: string);
begin
  if not Value then raise Exception.Create(Msg);
  Inc(Checks);
  WriteLn('[PASS] ', Msg);
end;
var
  Item: TItem;
  Extra, Existing, Statements: TStringList;
  SQL, N: string;
  Major: Integer;
  Failed: Boolean;
begin
  try
    Item := TItem.Create;
    Extra := TStringList.Create;
    Existing := TStringList.Create;
    Statements := TStringList.Create;
    try
      SQL := TDDLBuilder.CreateTableAndFields(Item, Extra, ddSQLite);
      Check(Pos('id INTEGER PRIMARY KEY AUTOINCREMENT', SQL) > 0, 'SQLite Int64 uses INTEGER rowid');
      SQL := TDDLBuilder.CreateTableAndFields(Item, Extra, ddPostgreSQL);
      Check(Pos('id BIGSERIAL', SQL) > 0, 'PostgreSQL Int64 uses BIGSERIAL');
      SQL := TDDLBuilder.CreateTableAndFields(Item, Extra, ddMySQL);
      Check(Pos('id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY', SQL) > 0, 'MySQL auto increment');
      Item.Id.DBOptions := [];
      Item.Code.DBOptions := [dboPrimaryKey, dboAutoInc];
      SQL := TDDLBuilder.CreateTableAndFields(Item, Extra, ddPostgreSQL);
      Check(Pos('code SERIAL', SQL) > 0, 'PostgreSQL Int32 uses SERIAL');
      Item.Id.DBOptions := [dboPrimaryKey, dboAutoInc];
      Item.Code.DBOptions := [];
      for Major := 2 to 5 do
      begin
        Extra.Clear;
        SQL := TDDLBuilder.CreateTableAndFields(Item, Extra, ddFirebird, False, Major);
        if Major = 2 then
        begin
          Check(Pos('IDENTITY', SQL) = 0, 'Firebird 2 has no identity syntax');
          Check(Extra.Count = 2, 'Firebird 2 creates generator and trigger');
          Check(Extra[0] = 'CREATE GENERATOR GEN_DM_AUTO_ID;', 'stable generator name');
          Check(Pos('NEW.id IS NULL', Extra[1]) > 0, 'trigger preserves explicit values, including zero');
          Check(Pos('GEN_ID(GEN_DM_AUTO_ID, 1); END', Extra[1]) > 0, 'trigger increments generator');
        end
        else
        begin
          Check(Pos('BIGINT GENERATED BY DEFAULT AS IDENTITY', SQL) > 0, 'Firebird ' + IntToStr(Major) + ' identity');
          Check(Extra.Count = 0, 'identity has no user generator or trigger');
        end;
        Extra.Clear;
        Existing.Clear;
        Existing.Add('code');
        Statements.Clear;
        TDDLBuilder.AddFieldStatements(Item, ddFirebird, Existing, Extra, Statements, False, Major);
        Check(Statements.Count = 1, 'ALTER adds only missing auto increment field');
        Check((Pos('IDENTITY', Statements.Text) > 0) = (Major >= 3), 'ALTER uses server capability');
        Check((Extra.Count = 2) = (Major = 2), 'ALTER legacy generator and trigger');
        Existing.Add('id');
        Extra.Clear;
        Statements.Clear;
        TDDLBuilder.AddFieldStatements(Item, ddFirebird, Existing, Extra, Statements, False, Major);
        Check((Extra.Count = 0) and (Statements.Count = 0), 'existing field is never recreated');
      end;
      Item.Id.DBOptions := [];
      Item.Code.DBOptions := [dboAutoInc];
      Extra.Clear;
      SQL := TDDLBuilder.CreateTableAndFields(Item, Extra, ddFirebird, False, 3);
      Check(Pos('code INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL', SQL) > 0, 'Firebird non-PK identity');
      Extra.Clear;
      SQL := TDDLBuilder.CreateTableAndFields(Item, Extra, ddFirebird, False, 2);
      Check(Extra.Count = 2, 'Firebird non-PK legacy auto increment');
      Check(TDDLBuilder.ParseFirebirdMajor('2.5.9') = 2, 'parse legacy server version');
      Check(TDDLBuilder.ParseFirebirdMajor(' 3.0.12 ') = 3, 'parse server version with spaces');
      Check(TDDLBuilder.ParseFirebirdMajor('10.0.1') = 10, 'parse multi-digit major');
      Failed := False;
      try TDDLBuilder.ParseFirebirdMajor('unknown'); except on E: Exception do Failed := True; end;
      Check(Failed, 'unknown version fails instead of guessing');
      N := TDDLBuilder.FirebirdObjectName('GEN', StringOfChar('a', 30), 'first');
      Check(Length(N) <= 31, 'legacy names fit 31 characters');
      Check(N <> TDDLBuilder.FirebirdObjectName('GEN', StringOfChar('a', 30), 'second'), 'long names retain distinct suffixes');
      Check(N = TDDLBuilder.FirebirdObjectName('GEN', StringOfChar('A', 30), 'FIRST'), 'unquoted names normalized before hashing');
      WriteLn('RESULT: ', Checks, ' auto increment unit checks passed');
    finally Statements.Free; Existing.Free; Extra.Free; Item.Free; end;
  except on E: Exception do begin WriteLn('[FAIL] ', E.Message); Halt(1); end; end;
end.
